databases:
  - name: crowdfunding
    plan: free
    databaseName: crowdfunding 
    user: admin 

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn crowdfunding_django.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crowdfunding
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_EMAIL
        value: "me@gmail.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "root"
