# Generated by Django 5.1.4 on 2025-01-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_campaigntable_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='donationtable',
            name='unique_donation',
        ),
        migrations.RemoveConstraint(
            model_name='purchasetable',
            name='unique_purchase',
        ),
    ]
